# Generated by Django 3.2 on 2022-05-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=150)),
                ('context', models.TextField(max_length=25000)),
                ('address', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
