# Generated by Django 3.2 on 2022-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='display_image',
            field=models.ImageField(default='', upload_to='hotels/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
