# Generated by Django 3.2 on 2022-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
