# Generated by Django 3.2 on 2022-06-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_activated',
            new_name='is_organisor',
        ),
    ]
