# Generated by Django 4.0.4 on 2022-05-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_alter_sitesettings_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
