# Generated by Django 4.0.4 on 2022-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='site@admin.gmail', max_length=254),
            preserve_default=False,
        ),
    ]
