# Generated by Django 4.0.4 on 2022-05-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=150)),
                ('context', models.TextField(max_length=25000)),
                ('days', models.IntegerField(default=1)),
                ('nights', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
