# Generated by Django 3.2 on 2022-06-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='context',
            new_name='content',
        ),
    ]
